-- Verification queries for the Campaign Analytics drill-down.
--
-- Generated by expanding the app's own query builders and substituting the binds, so these
-- are the statements the dashboard actually sends - not retyped from the source.
--
-- Campaign : demand_ai_internal_website_track
-- Window   : 2026-08-25 to 2026-09-24   (the Last 1 month preset)
--
-- If a figure disagrees with the screen, check the window first - the caption at the foot
-- of the page states the range it drew, and Snowflake's clock can differ from your own.
-- These run UNFILTERED. With 'Exclude internal traffic' ticked the app wraps the table in
-- a subquery dropping demandai.co visitors, which lowers the identity figures.

-- ============================================================================
-- Sessions  +  Events / Session
-- source: queries.campaign_detail_kpis_sql()
-- SESSIONS is the Sessions card. EVENTS / SESSIONS is the Events / Session card - the page
-- does that division in Python. This one row also gates every conditional section below.
-- ============================================================================
WITH ev AS (
        SELECT
            SESSION_ID, MESSAGE_ID, EVENT_TS, EVENT_NAME, EVENT_TYPE, TIMEZONE, REQUEST_IP,
            SEARCH_URL, REFERER_URL,
            PROPERTIES:campaign_name::STRING AS NAME,
            COALESCE(PROPERTIES:tenant_id::STRING, '(untagged)') AS TENANT,
            LOWER(NULLIF(TRIM(COALESCE(QUERY_PARAMETERS:email::STRING, QUERY_PARAMETERS:"amp;email"::STRING)), '')) AS ADDR,
            QUERY_PARAMETERS:asset::STRING AS ASSET,
            PROPERTIES:page_visited AS PAGE_VISITED,
            IFF(COALESCE(PROPERTIES:ml_request::STRING, '') = 'true', 1, 0) AS IS_AI,
            IFF((LOWER(REPLACE(EVENT_NAME, '_', ' ')) = 'form submit' AND NOT (LOWER(COALESCE(PROPERTIES:form_id::STRING, '')) LIKE '%cookie%' OR LOWER(COALESCE(PROPERTIES:form_id::STRING, '')) LIKE '%consent%' OR LOWER(COALESCE(PROPERTIES:form_id::STRING, '')) LIKE '%unsubscribe%' OR LOWER(COALESCE(PROPERTIES:form_id::STRING, '')) LIKE '%comment%' OR LOWER(COALESCE(PROPERTIES:form_id::STRING, '')) LIKE '%daicontactform%' OR LOWER(COALESCE(PROPERTIES:form_id::STRING, '')) LIKE '%rsrchgateform%')), 1, 0) AS IS_LEAD,
            IFF((LOWER(REPLACE(EVENT_NAME, '_', ' ')) = 'form submit' AND NOT (LOWER(COALESCE(PROPERTIES:form_id::STRING, '')) LIKE '%cookie%' OR LOWER(COALESCE(PROPERTIES:form_id::STRING, '')) LIKE '%consent%' OR LOWER(COALESCE(PROPERTIES:form_id::STRING, '')) LIKE '%unsubscribe%' OR LOWER(COALESCE(PROPERTIES:form_id::STRING, '')) LIKE '%comment%' OR LOWER(COALESCE(PROPERTIES:form_id::STRING, '')) LIKE '%daicontactform%' OR LOWER(COALESCE(PROPERTIES:form_id::STRING, '')) LIKE '%rsrchgateform%')), (COALESCE(SESSION_ID::STRING, '(no session)') || '|' || COALESCE(NULLIF(REGEXP_REPLACE(SEARCH_URL, '([?&](amp;)?email=)[^&]*', '\\1<redacted>'), ''), '(no page)')), NULL) AS LEAD_PAGE,
            IFF(COALESCE(PROPERTIES:form_id::STRING, '') = 'cookie-form', 1, 0) AS IS_COOKIE,
            -- The two halves of a consent decision, kept apart because they answer different
            -- questions and were previously in two unrelated places on the page.
            IFF(COALESCE(PROPERTIES:form_id::STRING, '') = 'cookie-form', 1, 0) AS IS_CONSENT_YES,
            IFF(PROPERTIES:attributes:consent IS NOT NULL, 1, 0) AS IS_CONSENT_NO,
            -- Projected here so the action chart can group on meaning rather than on EVENT_NAME;
            -- the label needs PROPERTIES, which does not survive this CTE's column list.
            
        CASE
            WHEN PROPERTIES:attributes:asset IS NOT NULL
              OR PROPERTIES:attributes:file IS NOT NULL THEN 'Opened content'
            WHEN LOWER(COALESCE(EVENT_NAME, '')) = 'visited'
                 AND PROPERTIES:asset IS NOT NULL THEN 'Opened content'
            WHEN PROPERTIES:attributes:category::STRING = 'query' THEN 'Asked a question'
            WHEN LOWER(COALESCE(EVENT_NAME, '')) = 'pdf-page-visit' THEN 'Read a document'
            WHEN LOWER(REPLACE(EVENT_NAME, '_', ' ')) = 'form submit' THEN 'Submitted a form'
            WHEN PROPERTIES:attributes:title IS NOT NULL
              OR PROPERTIES:attributes:click IS NOT NULL THEN 'Opened a link'
            WHEN PROPERTIES:attributes:dismiss IS NOT NULL THEN 'Dismissed a prompt'
            WHEN LOWER(COALESCE(EVENT_NAME, '')) IN ('clicked', 'button clicked') THEN 'Other click'
            ELSE INITCAP(LOWER(REPLACE(EVENT_NAME, '_', ' ')))
        END AS ACTION_LABEL,
            IFF((NOT (COALESCE(EVENT_TYPE, '') = 'page' OR COALESCE(LOWER(EVENT_NAME), '') = 'page visit') AND NOT (COALESCE(PROPERTIES:form_id::STRING, '') = 'cookie-form' OR PROPERTIES:attributes:consent IS NOT NULL OR LOWER(COALESCE(EVENT_NAME, '')) = 'consent-response')), 1, 0) AS IS_ACTION
        FROM CIT_DATA_CORE.TRACKING.INSYTE_TRAKING_EVENTS
        
        WHERE EVENT_TS::DATE BETWEEN '2026-08-25' AND '2026-09-24'
          AND CAMPAIGN_ID = 'demand_ai_internal_website_track'
          AND (EVENT_NAME IS NULL OR LOWER(EVENT_NAME) NOT IN ('test event', 'test download event'))
    
        ), sess AS (
            SELECT
                SESSION_ID,
                MAX(IS_AI) AS USED_AI,
                MAX(IS_LEAD) AS CONVERTED,
                MAX(IS_ACTION) AS ACTED,
                MAX(IS_CONSENT_YES) AS SAID_YES,
                MAX(IS_CONSENT_NO) AS SAID_NO,
                MAX(IFF(ASSET IS NOT NULL, 1, 0)) AS SAW_CONTENT,
                MAX(IFF(ADDR LIKE '%@%.%', 1, 0)) AS IDENTIFIED,
                COUNT(DISTINCT MESSAGE_ID) AS EVENTS,
                DATEDIFF('second', MIN(EVENT_TS), MAX(EVENT_TS)) AS SECS,
                -- MODE, not MIN: 2.8% of sessions carry more than one REQUEST_IP, and the
                -- dominant address describes the session better than an arbitrary one.
                MODE(REQUEST_IP) AS IP
            FROM ev
            WHERE SESSION_ID IS NOT NULL
            GROUP BY SESSION_ID
        ), ev_agg AS (
            -- One pass over the events, not one pass per column. Written as 13 scalar
            -- subqueries first, which measured 4-6s because each re-scanned the CTE;
            -- folded into a single aggregate row it lands near a second. This query is on
            -- the critical path of every drill-in, so it is the one worth flattening.
            SELECT
                MODE(NAME) AS CAMPAIGN_NAME,
                MODE(TENANT) AS TENANT,
                COUNT(DISTINCT MESSAGE_ID) AS EVENTS,
                MIN(EVENT_TS)::DATE AS FIRST_SEEN,
                MAX(EVENT_TS)::DATE AS LAST_SEEN,
                COUNT(DISTINCT EVENT_TS::DATE) AS ACTIVE_DAYS,
                COUNT(DISTINCT ASSET) AS ASSETS,
                COUNT(DISTINCT IFF(ADDR LIKE '%@%.%', ADDR, NULL)) AS PEOPLE,
                COUNT(DISTINCT IFF(ADDR LIKE '%@%.%', SPLIT_PART(ADDR, '@', 2), NULL)) AS COMPANIES,
                COUNT(DISTINCT LEAD_PAGE) AS LEAD_PAGE_SUBMITS,
                COUNT(DISTINCT IFF(IS_AI = 1, MESSAGE_ID, NULL)) AS AI_EVENTS,
                COUNT(DISTINCT IFF(PAGE_VISITED IS NOT NULL, MESSAGE_ID, NULL)) AS PDF_EVENTS,
                COUNT(DISTINCT IFF(COALESCE(REFERER_URL, '') <> '', REFERER_URL, NULL)) AS REFERRERS,
                -- The gate for the Pages section, counted here rather than asked for separately:
                -- collect() needs to know whether the section has anything in it BEFORE deciding
                -- to query it, and the CTE already projects SEARCH_URL, EVENT_NAME and EVENT_TYPE,
                -- so both expressions resolve against it without a second scan.
                COUNT(DISTINCT IFF((COALESCE(EVENT_TYPE, '') = 'page' OR COALESCE(LOWER(EVENT_NAME), '') = 'page visit') AND (COALESCE(PARSE_URL(SEARCH_URL, 1):host::STRING, '') NOT IN ('localhost', '127.0.0.1') AND COALESCE(PARSE_URL(SEARCH_URL, 1):host::STRING, '') <> ''), COALESCE(PARSE_URL(SEARCH_URL, 1):host::STRING, '') || '/' || COALESCE(PARSE_URL(SEARCH_URL, 1):path::STRING, ''), NULL)) AS PAGES,
                COUNT(DISTINCT IFF((COALESCE(EVENT_TYPE, '') = 'page' OR COALESCE(LOWER(EVENT_NAME), '') = 'page visit') AND (COALESCE(PARSE_URL(SEARCH_URL, 1):host::STRING, '') NOT IN ('localhost', '127.0.0.1') AND COALESCE(PARSE_URL(SEARCH_URL, 1):host::STRING, '') <> ''), MESSAGE_ID, NULL)) AS PAGE_VIEWS,
                COUNT(DISTINCT TIMEZONE) AS TIMEZONES
            FROM ev
        ), sess_agg AS (
            SELECT
                COUNT(*) AS SESSIONS,
                COALESCE(SUM(USED_AI), 0) AS AI_SESSIONS,
                COALESCE(SUM(CONVERTED), 0) AS LEAD_SESSIONS,
                COALESCE(SUM(ACTED), 0) AS ACTED_SESSIONS,
                COALESCE(SUM(SAID_YES), 0) AS CONSENT_YES_SESSIONS,
                COALESCE(SUM(SAID_NO), 0) AS CONSENT_NO_SESSIONS,
                COALESCE(SUM(SAW_CONTENT), 0) AS CONTENT_SESSIONS,
                COALESCE(SUM(IDENTIFIED), 0) AS IDENTIFIED_SESSIONS,
                COALESCE((APPROX_PERCENTILE(EVENTS, 0.5))::FLOAT, 0) AS MEDIAN_EVENTS,
                COALESCE((APPROX_PERCENTILE(SECS, 0.5) / 60.0)::FLOAT, 0) AS MEDIAN_DURATION_MINUTES,
                COALESCE((AVG(SECS) / 60.0)::FLOAT, 0) AS MEAN_DURATION_MINUTES,
                COALESCE(SUM(IFF(SECS = 0, 1, 0)), 0) AS INSTANT_SESSIONS
            FROM sess
        ), ip_agg AS (
            -- How concentrated is this campaign's traffic on one network address? Sessions
            -- are the reach figure everything else divides by, and a session count says
            -- nothing about how many PLACES it came from: sas-kr-ai reports 271 sessions,
            -- of which 266 share a single address. Measured across 169 campaigns with 50+
            -- sessions, the top address takes a median 20% but reaches 98% on a handful -
            -- the distribution is bimodal, not a gradient, so a threshold is meaningful here.
            --
            -- An address is NOT a person: a corporate NAT hides a whole office behind one.
            -- That is precisely why this is worth stating rather than charting - it bounds
            -- how the session count may be read, and claims nothing about who.
            SELECT COUNT(*) AS DISTINCT_IPS, COALESCE(MAX(N), 0) AS TOP_IP_SESSIONS
            FROM (SELECT IP, COUNT(*) AS N FROM sess WHERE IP IS NOT NULL GROUP BY IP)
        )
        SELECT * FROM ev_agg CROSS JOIN sess_agg CROSS JOIN ip_agg;

-- ============================================================================
-- Events donut
-- source: queries.campaign_event_mix_sql()
-- Three exclusive buckets, AI requests excluded. The BUCKET totals are the ring, their sum is
-- the number in the hole, and EVENTS above minus that sum is the AI figure in the caption.
-- ============================================================================
SELECT
            
        CASE
            WHEN COALESCE(LOWER(REPLACE(EVENT_NAME, '_', ' ')), '') = 'form submit' THEN 'Form submit'
            WHEN (COALESCE(EVENT_TYPE, '') = 'page' OR COALESCE(LOWER(EVENT_NAME), '') = 'page visit') THEN 'Page visit'
            ELSE 'Clicks'
        END AS BUCKET,
            COUNT(DISTINCT MESSAGE_ID) AS EVENTS
        FROM CIT_DATA_CORE.TRACKING.INSYTE_TRAKING_EVENTS
        
        WHERE EVENT_TS::DATE BETWEEN '2026-08-25' AND '2026-09-24'
          AND CAMPAIGN_ID = 'demand_ai_internal_website_track'
          AND (EVENT_NAME IS NULL OR LOWER(EVENT_NAME) NOT IN ('test event', 'test download event'))
        GROUP BY 1;

-- ============================================================================
-- Activity over time
-- source: queries.campaign_daily_sql()
-- One row per day; SESSION_COUNT is the bar height.
-- ============================================================================
SELECT
            EVENT_TS::DATE AS EVENT_DATE,
            COUNT(DISTINCT SESSION_ID) AS SESSION_COUNT,
            COUNT(DISTINCT MESSAGE_ID) AS EVENT_COUNT
        FROM CIT_DATA_CORE.TRACKING.INSYTE_TRAKING_EVENTS
        
        WHERE EVENT_TS::DATE BETWEEN '2026-08-25' AND '2026-09-24'
          AND CAMPAIGN_ID = 'demand_ai_internal_website_track'
          AND (EVENT_NAME IS NULL OR LOWER(EVENT_NAME) NOT IN ('test event', 'test download event'))
        GROUP BY EVENT_DATE
        ORDER BY EVENT_DATE;

-- ============================================================================
-- Session quality
-- source: queries.campaign_duration_bands_sql()
-- The duration-band bars. The sentence above them comes from the KPI query's
-- MEDIAN_DURATION_MINUTES, MEAN_DURATION_MINUTES, INSTANT_SESSIONS and MEDIAN_EVENTS.
-- ============================================================================
WITH s AS (
            SELECT SESSION_ID, DATEDIFF('second', MIN(EVENT_TS), MAX(EVENT_TS)) AS DURATION_SECONDS
            FROM CIT_DATA_CORE.TRACKING.INSYTE_TRAKING_EVENTS
            
        WHERE EVENT_TS::DATE BETWEEN '2026-08-25' AND '2026-09-24'
          AND CAMPAIGN_ID = 'demand_ai_internal_website_track'
          AND (EVENT_NAME IS NULL OR LOWER(EVENT_NAME) NOT IN ('test event', 'test download event'))
              AND SESSION_ID IS NOT NULL
            GROUP BY SESSION_ID
        )
        SELECT
            CASE
                WHEN DURATION_SECONDS = 0 THEN '0s (instant)'
                WHEN DURATION_SECONDS <= 10 THEN '1-10 seconds'
                WHEN DURATION_SECONDS <= 60 THEN '10-60 seconds'
                WHEN DURATION_SECONDS <= 300 THEN '1-5 minutes'
                WHEN DURATION_SECONDS <= 1800 THEN '5-30 minutes'
                WHEN DURATION_SECONDS <= 7200 THEN '30 min - 2 hours'
                ELSE 'over 2 hours'
            END AS BAND,
            CASE
                WHEN DURATION_SECONDS = 0 THEN 1
                WHEN DURATION_SECONDS <= 10 THEN 2
                WHEN DURATION_SECONDS <= 60 THEN 3
                WHEN DURATION_SECONDS <= 300 THEN 4
                WHEN DURATION_SECONDS <= 1800 THEN 5
                WHEN DURATION_SECONDS <= 7200 THEN 6
                ELSE 7
            END AS BAND_ORDER,
            COUNT(*) AS SESSIONS
        FROM s
        GROUP BY BAND, BAND_ORDER
        ORDER BY BAND_ORDER;

-- ============================================================================
-- Where they are
-- source: queries.campaign_geo_sql()
-- Both breakdowns in one scan - filter KIND='region' for the chart, KIND='timezone' for the
-- table beneath it.
-- ============================================================================
WITH base AS (
            SELECT SESSION_ID, TIMEZONE
            FROM CIT_DATA_CORE.TRACKING.INSYTE_TRAKING_EVENTS
            
        WHERE EVENT_TS::DATE BETWEEN '2026-08-25' AND '2026-09-24'
          AND CAMPAIGN_ID = 'demand_ai_internal_website_track'
          AND (EVENT_NAME IS NULL OR LOWER(EVENT_NAME) NOT IN ('test event', 'test download event'))
              AND SESSION_ID IS NOT NULL
        ), region AS (
            SELECT 'region' AS KIND, 
        CASE
            WHEN TIMEZONE IS NULL OR TRIM(TIMEZONE) = '' THEN 'Unknown'
            WHEN TIMEZONE IN ('UTC', 'GMT') OR TIMEZONE ILIKE 'Etc/%' THEN 'Unknown / UTC'
            WHEN POSITION('/' IN TIMEZONE) > 0 THEN SPLIT_PART(TIMEZONE, '/', 1)
            ELSE 'Unknown / UTC'
        END AS LABEL, COUNT(DISTINCT SESSION_ID) AS SESSIONS
            FROM base GROUP BY 1, 2
        ), tz AS (
            SELECT 'timezone' AS KIND, TIMEZONE AS LABEL, COUNT(DISTINCT SESSION_ID) AS SESSIONS
            FROM base
            WHERE TIMEZONE IS NOT NULL AND TRIM(TIMEZONE) <> ''
            GROUP BY 1, 2
            QUALIFY ROW_NUMBER() OVER (ORDER BY SESSIONS DESC) <= 10
        )
        SELECT * FROM region
        UNION ALL SELECT * FROM tz
        ORDER BY KIND, SESSIONS DESC;

-- ============================================================================
-- Pages
-- source: queries.campaign_pages_sql()
-- Query strings are stripped before grouping - QUERY_PARAMETERS:email rides in them on
-- personalised links, so grouping on the raw URL would put addresses in the output.
-- ============================================================================
WITH base AS (
            SELECT SESSION_ID, MESSAGE_ID, EVENT_NAME, EVENT_TYPE, SEARCH_URL,
                   COALESCE(PARSE_URL(SEARCH_URL, 1):scheme::STRING, 'https') AS SCHEME
            FROM CIT_DATA_CORE.TRACKING.INSYTE_TRAKING_EVENTS
            
        WHERE EVENT_TS::DATE BETWEEN '2026-08-25' AND '2026-09-24'
          AND CAMPAIGN_ID = 'demand_ai_internal_website_track'
          AND (EVENT_NAME IS NULL OR LOWER(EVENT_NAME) NOT IN ('test event', 'test download event'))
              AND SESSION_ID IS NOT NULL
        ), all_sessions AS (
            SELECT COUNT(DISTINCT SESSION_ID) AS N FROM base
        ), grouped AS (
            SELECT
                COALESCE(PARSE_URL(SEARCH_URL, 1):host::STRING, '') AS HOST,
                '/' || COALESCE(PARSE_URL(SEARCH_URL, 1):path::STRING, '') AS PATH,
                COALESCE(PARSE_URL(SEARCH_URL, 1):host::STRING, '') || '/' || COALESCE(PARSE_URL(SEARCH_URL, 1):path::STRING, '') AS PAGE_URL,
                MODE(SCHEME) AS SCHEME,
                COUNT(DISTINCT SESSION_ID) AS SESSIONS,
                COUNT(DISTINCT MESSAGE_ID) AS VIEWS,
                ROUND(COUNT(DISTINCT MESSAGE_ID) * 1.0
                      / NULLIF(COUNT(DISTINCT SESSION_ID), 0), 1) AS VIEWS_PER_SESSION,
                COALESCE((COUNT(DISTINCT SESSION_ID) * 100.0
                    / NULLIF((SELECT N FROM all_sessions), 0))::FLOAT, 0) AS PCT_OF_SESSIONS
            FROM base
            WHERE (COALESCE(EVENT_TYPE, '') = 'page' OR COALESCE(LOWER(EVENT_NAME), '') = 'page visit')
              AND SEARCH_URL IS NOT NULL
              AND (COALESCE(PARSE_URL(SEARCH_URL, 1):host::STRING, '') NOT IN ('localhost', '127.0.0.1') AND COALESCE(PARSE_URL(SEARCH_URL, 1):host::STRING, '') <> '')
            GROUP BY 1, 2, 3
        )
        SELECT
            IFF(COUNT(*) OVER (PARTITION BY PATH) > 1, PAGE_URL, PATH) AS PAGE,
            SESSIONS,
            VIEWS,
            VIEWS_PER_SESSION,
            PCT_OF_SESSIONS,
            HOST,
            SCHEME || '://' || HOST || PATH AS URL
        FROM grouped
        ORDER BY SESSIONS DESC
        LIMIT 12;

-- ============================================================================
-- How they arrived
-- source: queries.campaign_sources_sql()
-- Also two-in-one: KIND='group' is the source mix, KIND='referrer' the external referrers.
-- ============================================================================
WITH base AS (
            SELECT MESSAGE_ID, REFERER_URL
            FROM CIT_DATA_CORE.TRACKING.INSYTE_TRAKING_EVENTS
            
        WHERE EVENT_TS::DATE BETWEEN '2026-08-25' AND '2026-09-24'
          AND CAMPAIGN_ID = 'demand_ai_internal_website_track'
          AND (EVENT_NAME IS NULL OR LOWER(EVENT_NAME) NOT IN ('test event', 'test download event'))
        ), grp AS (
            SELECT 'group' AS KIND, 
        CASE
            WHEN COALESCE(REFERER_URL, '') = '' THEN 'Direct / none'
            WHEN PARSE_URL(REFERER_URL, 1):host::STRING IN ('localhost', '127.0.0.1')
              OR PARSE_URL(REFERER_URL, 1):host::STRING ILIKE '%amplifye.ai'
              OR PARSE_URL(REFERER_URL, 1):host::STRING ILIKE '%demandai.net'
              OR PARSE_URL(REFERER_URL, 1):host::STRING ILIKE '%atlassian.net'
              OR PARSE_URL(REFERER_URL, 1):host::STRING ILIKE '%amplifyapp.com'
              OR PARSE_URL(REFERER_URL, 1):host::STRING ILIKE '%amazonaws.com'
              OR PARSE_URL(REFERER_URL, 1):host::STRING ILIKE '%cloudfront.net' THEN 'Internal / dev'
            WHEN PARSE_URL(REFERER_URL, 1):host::STRING ILIKE '%officeapps.live.com'
              OR PARSE_URL(REFERER_URL, 1):host::STRING ILIKE '%sharepoint.com'
              OR PARSE_URL(REFERER_URL, 1):host::STRING ILIKE '%office.net'
              OR PARSE_URL(REFERER_URL, 1):host::STRING ILIKE '%microsoft.com' THEN 'Email / Office'
            ELSE 'External'
        END AS LABEL,
                   COUNT(DISTINCT MESSAGE_ID) AS EVENTS
            FROM base GROUP BY 1, 2
        ), ref AS (
            SELECT 'referrer' AS KIND, PARSE_URL(REFERER_URL, 1):host::STRING AS LABEL,
                   COUNT(DISTINCT MESSAGE_ID) AS EVENTS
            FROM base
            WHERE 
        CASE
            WHEN COALESCE(REFERER_URL, '') = '' THEN 'Direct / none'
            WHEN PARSE_URL(REFERER_URL, 1):host::STRING IN ('localhost', '127.0.0.1')
              OR PARSE_URL(REFERER_URL, 1):host::STRING ILIKE '%amplifye.ai'
              OR PARSE_URL(REFERER_URL, 1):host::STRING ILIKE '%demandai.net'
              OR PARSE_URL(REFERER_URL, 1):host::STRING ILIKE '%atlassian.net'
              OR PARSE_URL(REFERER_URL, 1):host::STRING ILIKE '%amplifyapp.com'
              OR PARSE_URL(REFERER_URL, 1):host::STRING ILIKE '%amazonaws.com'
              OR PARSE_URL(REFERER_URL, 1):host::STRING ILIKE '%cloudfront.net' THEN 'Internal / dev'
            WHEN PARSE_URL(REFERER_URL, 1):host::STRING ILIKE '%officeapps.live.com'
              OR PARSE_URL(REFERER_URL, 1):host::STRING ILIKE '%sharepoint.com'
              OR PARSE_URL(REFERER_URL, 1):host::STRING ILIKE '%office.net'
              OR PARSE_URL(REFERER_URL, 1):host::STRING ILIKE '%microsoft.com' THEN 'Email / Office'
            ELSE 'External'
        END = 'External'
            GROUP BY 1, 2
            QUALIFY ROW_NUMBER() OVER (ORDER BY EVENTS DESC) <= 8
        )
        SELECT * FROM grp
        UNION ALL SELECT * FROM ref
        ORDER BY KIND, EVENTS DESC;

-- ============================================================================
-- AI usage
-- source: queries.campaign_ai_sql()
-- Model mix. Empty unless the campaign has AI activity.
-- ============================================================================
SELECT
            
        CASE
            WHEN PROPERTIES:llm::STRING ILIKE '%opus-4-6%'   THEN 'Claude Opus 4.6'
            WHEN PROPERTIES:llm::STRING ILIKE '%sonnet-4-6%' THEN 'Claude Sonnet 4.6'
            WHEN PROPERTIES:llm::STRING ILIKE '%3-5-sonnet%' THEN 'Claude 3.5 Sonnet'
            WHEN PROPERTIES:llm IS NULL
              OR LOWER(PROPERTIES:llm::STRING) IN ('undefined', 'null', '') THEN 'Unrecorded'
            ELSE REGEXP_REPLACE(PROPERTIES:llm::STRING, '^[a-z]{2}\\.', '')
        END AS MODEL,
            COUNT(DISTINCT MESSAGE_ID) AS REQUESTS,
            COUNT(DISTINCT SESSION_ID) AS SESSIONS
        FROM CIT_DATA_CORE.TRACKING.INSYTE_TRAKING_EVENTS
        
        WHERE EVENT_TS::DATE BETWEEN '2026-08-25' AND '2026-09-24'
          AND CAMPAIGN_ID = 'demand_ai_internal_website_track'
          AND (EVENT_NAME IS NULL OR LOWER(EVENT_NAME) NOT IN ('test event', 'test download event'))
          AND COALESCE(PROPERTIES:ml_request::STRING, '') = 'true'
        GROUP BY 1
        ORDER BY REQUESTS DESC;
